name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # Schedule daily updates
  workflow_dispatch:                  # Allow manual run
  push: { branches: ["main"] }        # Optional: Run on pushes to main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: rishabhpathak359  # Change to your username
          committer_message: "chore: update metrics"

          # Basic Configurations
          template: classic
          base: header, activity, community, repositories, metadata  # Basic profile info
          config_timezone: America/New_York  # Adjust to your timezone

          # Plugin Settings
          plugin_introduction: yes  # Show general account information

          # Activity Calendar in 3D Isometric View
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Programming Languages Stats
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          # Achievements Display
          plugin_achievements: yes
          plugin_achievements_display: detailed  # Show detailed badges info

          # Activity Calendar over the Years
          plugin_calendar: yes
          plugin_calendar_limit: 2

          # Habits & Weekly Activity Analysis
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # License Information
          plugin_licenses: yes
          plugin_licenses_setup: npm ci  # Adjust as per your repo’s package manager

          # Skyline 3D View of Contributions
          plugin_skyline: yes
          plugin_skyline_year: 2022  # Set preferred year
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1

          # Stargazers Analysis (Smooth Chartist Lines)
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist

          # Support (Sponsorship) Section
          plugin_support: yes

          # Topics Used in Repositories (Icons Mode)
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
